directories:
  output: release/${version}
  buildResources: build
appId: com.biolab.iqc
productName: Hệ thống QC Phòng xét nghiệm
icon: build/icon.ico
asar: true
forceCodeSigning: false
buildDependenciesFromSource: false
files:
  - filter:
      - dist-electron
      - dist
      - public/logo.svg
mac:
  artifactName: ${productName}_${version}.${ext}
  target:
    - dmg
win:
  target:
    - target: dir
      arch:
        - x64
  artifactName: IQC-App_${version}_${arch}
  icon: build/icon.ico
  sign: false
  verifyUpdateCodeSignature: false
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Hệ thống QC Phòng xét nghiệm
electronVersion: 22.3.27
